import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import Topbar from "../components/Topbar";
import SearchHeader from "../components/SearchHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "FeelUp",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head></head>
      <body className="antialiased">
        <Providers>
          <div className="flex">
            <Sidebar />
            <div className="flex-1 min-h-screen">
              <div className="sticky top-0 z-40 bg-white/70 backdrop-blur-lg border-b border-gray-100 shadow-sm">
                <div className="max-w-7xl mx-auto px-6 py-3 flex items-center gap-6">
                  <div className="flex items-center md:hidden">
                    <Navbar />
                  </div>

                  <SearchHeader />

                  <div className="flex items-center">
                    <Topbar />
                  </div>
                </div>
              </div>

              <main>{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
